version: '3.1'

services:
    php:
        build: services/php
        working_dir: /application
        volumes:
            - ./src:/application
            - ./services/php.ini:/usr/local/etc/php/php.ini
            - ./services/apache.conf:/etc/apache2/sites-enabled/000-default.conf
        environment:
            - VIRTUAL_HOST=php.dev
        networks:
            - nginx-proxy
            - code-network

    mysql:
        image: mysql:5.7
        volumes:
            - ./services/mysql:/var/lib/mysql
            - ./services/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root-password
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
    nginx-proxy:
        external: true
