version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: ${PORTAINER_CMD}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/etc/nginx/certs

  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/default_location:/etc/nginx/vhost.d/default_location:ro

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    networks:
      - mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.conf:/etc/mysql/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

networks:
  nginx-proxy:
    external: true
  mysql:
    external: true
