version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/srv/app
    networks:
      - default
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
  mysql:
    image: mysql:5.7
    expose:
     - 3306
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379

networks:
  nginx-proxy:
    external: true
