version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./.docker/nginx/helpers:/etc/nginx/helpers:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/public:/srv/app/public:${VOLUME_CACHING}
    networks:
      - default
      - nginx-proxy
    restart: ${RESTART_POLICY}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  php:
    image: wiejeben/php:7.1
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./app:/srv/app:${VOLUME_CACHING}
    networks:
      - default
      - mysql
    restart: ${RESTART_POLICY}
    environment:
      XDEBUG_CONFIG: remote_port=${XDEBUG_PORT}
      XDEBUG_ENABLE: ${XDEBUG_ENABLE}
      REDIS_ENABLE: ${REDIS_ENABLE}
      COMPOSER_ENABLE: ${COMPOSER_ENABLE}

  redis:
    image: redis:4.0-alpine
    restart: ${RESTART_POLICY}

networks:
  nginx-proxy:
    external: true
  mysql:
    external: true