version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/000-default.conf:ro
      - ./.docker/nginx/helpers:/etc/nginx/helpers:ro
      - .:/srv/app:delegated
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  php:
    build: ./.docker
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - .:/srv/app:delegated
    environment:
      PHP_XDEBUG_ENABLED: ${XDEBUG_ENABLE}
      XDEBUG_CONFIG: remote_port=${XDEBUG_PORT}

  mysql:
    image: mysql:5.7
    volumes:
      - ./.docker/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379

networks:
  default:
    external:
      name: nginx-proxy
