version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    networks:
      - nginx-proxy
    ports:
      - 8080:8080
    restart: ${RESTART_POLICY}
    environment:
      JENKINS_HOST_HOME: "/data"
    user: jenkins
    volumes:
      - ./data:/var/jenkins_home:${VOLUME_CACHING}
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nginx-proxy:
    external: true