version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    networks:
      - nginx-proxy
    restart: ${RESTART_POLICY}
    volumes:
      - ./data:/var/jenkins_home:${VOLUME_CACHING}
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nginx-proxy:
    external: true